### ISSUE TITLE
Many examples not working

### ISSUE THREAD

**Issue by Evidlo** [PyLops/pylops#415]
I tried out the Radon2D example [here](https://pylops.readthedocs.io/en/latest/tutorials/ctscan.html#sphx-glr-download-tutorials-ctscan-py) and got a dimension error.

I think maybe there is a ravel/unravel missing?

``` python
>>> %run ctscan.py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/research/pylops_test/ctscan.py:65, in <module>
     52 theta = np.linspace(0.0, np.pi, ntheta, endpoint=False)
     54 RLop = pylops.signalprocessing.Radon2D(
     55     np.arange(ny),
     56     np.arange(nx),
   (...)
     62     dtype="float64",
     63 )
---> 65 y = RLop.H * x
     67 ###############################################################################
     68 # We can now first perform the adjoint, which in the medical imaging literature
     69 # is also referred to as back-projection.
   (...)
     72 # back-projection, which simply applies a correction filter in the
     73 # frequency domain to the adjoint model.
     74 xrec = RLop * y

File ~/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py:91, in LinearOperator.__mul__(self, x)
     90 def __mul__(self, x):
---> 91     y = super().__mul__(x)
     92     if isinstance(y, spLinearOperator):
     93         y = aslinearoperator(y)

File ~/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py:393, in LinearOperator.__mul__(self, x)
    392 def __mul__(self, x):
--> 393     return self.dot(x)

File ~/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py:262, in LinearOperator.dot(self, x)
    260     return self.matvec(x)
    261 elif x.ndim == 2:
--> 262     return self.matmat(x)
    263 else:
    264     raise ValueError("expected 1-d or 2-d array or matrix, got %r" % x)

File ~/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py:207, in LinearOperator.matmat(self, X)
    205     raise ValueError("expected 2-d ndarray or matrix, " "not %d-d" % X.ndim)
    206 if X.shape[0] != self.shape[1]:
--> 207     raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
    208 Y = self._matmat(X)
    209 return Y

ValueError: dimension mismatch: (29445, 33150), (170, 195)
```

**Comment by Evidlo** [comment]
It seems like maybe there were some API changes recently that broke some of the examples.  I tried running each one in the `examples/` folder:

<details>

<pre>

[evan@blackbox examples] for f in *.py; do err=$(python $f 2>&1); if (( $? != 0 )); then echo -e "\n-------------- $f ----------- \n" >> /tmp/fail; echo "$err" >> /tmp/fail; fi; done

-------------- plot_avo.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_avo.py", line 82, in <module>
    dPP_const = PPop_const * m
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (10521, 1503), (501, 3)

-------------- plot_bilinear.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_bilinear.py", line 31, in <module>
    y = Bop * x
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (2000, 31570), (154, 205)

-------------- plot_causalintegration.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_causalintegration.py", line 81, in <module>
    xreg = pylops.optimization.leastsquares.regularized_inversion(
AttributeError: module 'pylops.optimization.leastsquares' has no attribute 'regularized_inversion'. Did you mean: 'RegularizedInversion'?

-------------- plot_cgls.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_cgls.py", line 42, in <module>
    xest, istop, nit, r1norm, r2norm, cost_cgls = pylops.optimization.basic.cgls(
AttributeError: module 'pylops.optimization' has no attribute 'basic'

-------------- plot_chirpradon.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_chirpradon.py", line 62, in <module>
    dL_chirp = R2Op * d
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (2601, 2601), (51, 51)

-------------- plot_convolve.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_convolve.py", line 96, in <module>
    Cop = pylops.signalprocessing.Convolve2D(
TypeError: Convolve2D() missing 1 required positional argument: 'dims'

-------------- plot_derivative.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_derivative.py", line 86, in <module>
    D1op = pylops.FirstDerivative((nx, ny), axis=0, dtype="float64")
TypeError: FirstDerivative.__init__() got an unexpected keyword argument 'axis'

-------------- plot_diagonal.py ----------- 

x =
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
y = D*x =
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
xadj = D'*x =
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
x =
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_diagonal.py", line 98, in <module>
    Dop = pylops.Diagonal(d, dims=(nx, ny), axis=0)
TypeError: Diagonal.__init__() got an unexpected keyword argument 'axis'

-------------- plot_flip.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_flip.py", line 44, in <module>
    Fop = pylops.Flip((nt, nx), axis=0)
TypeError: Flip.__init__() got an unexpected keyword argument 'axis'

-------------- plot_ista.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_ista.py", line 54, in <module>
    x_mp = pylops.optimization.sparsity.omp(
AttributeError: module 'pylops.optimization.sparsity' has no attribute 'omp'. Did you mean: 'OMP'?

-------------- plot_linearregr.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_linearregr.py", line 119, in <module>
    class CallbackIRLS(pylops.optimization.callback.Callbacks):
AttributeError: module 'pylops.optimization' has no attribute 'callback'

-------------- plot_matrixmult.py ----------- 

A= [[0.37777156 0.7496155  0.         0.24633798 0.4354716 ]
 [0.         0.90400603 0.29743689 0.69043322 0.        ]
 [0.14528699 0.55209071 0.         0.36619844 0.87284389]
 [0.79913676 0.1909229  0.73615116 0.69106882 0.77903644]
 [0.37648255 0.         0.01917825 0.84064844 0.        ]]
A^-1= [[ 1.95254832 -0.90580801 -1.29050952  0.35445584  0.44256587]
 [ 0.9662563   0.53134822 -0.30025745 -0.20371229 -0.42128558]
 [-0.95764934  0.85050153 -0.45299657  1.04285799 -1.07786925]
 [-0.85259698  0.38626108  0.58828634 -0.18253365  1.01594588]
 [-0.57847837 -0.34736852  1.30359399  0.14643326 -0.23343121]]
eigs= [ 2.12268176+0.j         -0.48995893+0.50488884j -0.48995893-0.50488884j]
x= [1. 1. 1. 1. 1.]
y= [1.80919665 1.89187614 1.93642004 3.19631608 1.23630924]
lsqr solution xest= [1. 1. 1. 1. 1.]
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_matrixmult.py", line 206, in <module>
    Aop = pylops.MatrixMult(A, otherdims=(3,), dtype="float64")
TypeError: MatrixMult.__init__() got an unexpected keyword argument 'otherdims'

-------------- plot_mdc.py ----------- 

/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/waveeqprocessing/mdd.py:55: FutureWarning: A new implementation of MDC is provided in v1.5.0. This currently affects only the inner working of the operator, end-users can continue using the operator in the same way. Nevertheless, it is now recommended to start using the operator with transpose=True, as this behaviour will become default in version v2.0.0 and the behaviour with transpose=False will be deprecated.
  warnings.warn(
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_mdc.py", line 89, in <module>
    d = MDCop * m.ravel()
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 260, in dot
    return self.matvec(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 141, in matvec
    raise ValueError("dimension mismatch")
ValueError: dimension mismatch

-------------- plot_nmo.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_nmo.py", line 22, in <module>
    from pylops.utils.decorators import reshaped
ModuleNotFoundError: No module named 'pylops.utils.decorators'

-------------- plot_pad.py ----------- 

x = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
P*x = [ 0.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.  0.  0.  0.]
P'*y = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_pad.py", line 38, in <module>
    y = Pop * x
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (66, 20), (5, 4)

-------------- plot_patching.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_patching.py", line 64, in <module>
    fftdata = Slid.H * data
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (648960, 28000), (140, 200)

-------------- plot_prestack.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_prestack.py", line 80, in <module>
    dPP_const = PPop_const * m
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (10521, 1503), (501, 3)

-------------- plot_radon.py ----------- 

/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/signalprocessing/Radon2D.py:32: RuntimeWarning: divide by zero encountered in true_divide
  return np.sqrt(t ** 2 + (x / px) ** 2)
/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/signalprocessing/Radon2D.py:32: RuntimeWarning: invalid value encountered in true_divide
  return np.sqrt(t ** 2 + (x / px) ** 2)
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_radon.py", line 48, in <module>
    yL = RLop * x
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (2091, 1681), (41, 41)

-------------- plot_regr.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_regr.py", line 116, in <module>
    xirls, nouter = pylops.optimization.sparsity.irls(
AttributeError: module 'pylops.optimization.sparsity' has no attribute 'irls'

-------------- plot_restriction.py ----------- 

WARNING: at least one value is beyond penultimate sample, forced to be at penultimate sample
/home/evan/resources/pylops/examples/plot_restriction.py:84: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_restriction.py", line 99, in <module>
    Rop = pylops.Restriction((nx, nt), iava, axis=0, dtype="float64")
TypeError: Restriction.__init__() got an unexpected keyword argument 'axis'

-------------- plot_roll.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_roll.py", line 41, in <module>
    Rop = pylops.Roll(dims=(ny, nx), axis=1, shift=-2)
TypeError: Roll.__init__() got an unexpected keyword argument 'axis'

-------------- plot_seislet.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_seislet.py", line 74, in <module>
    seis = Sop * d
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (51200, 51200), (256, 200)

-------------- plot_shift.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_shift.py", line 60, in <module>
    wav2dshift = Op * wav2d
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (1270, 1270), (127, 10)

-------------- plot_sliding.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_sliding.py", line 67, in <module>
    axs[1].plot(Op.f, np.abs(x[i, :]), label=f"Window {i+1}/{nwins}")
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

-------------- plot_slopeest.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_slopeest.py", line 32, in <module>
    from pylops.utils.signalprocessing import dip_estimate, slope_estimate
ImportError: cannot import name 'dip_estimate' from 'pylops.utils.signalprocessing' (/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/utils/signalprocessing.py)

-------------- plot_smoothing1d.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_smoothing1d.py", line 69, in <module>
    Sop = pylops.Smoothing1D(nsmooth=5, dims=(11, 21), axis=0, dtype="float64")
TypeError: Smoothing1D() got an unexpected keyword argument 'axis'

-------------- plot_smoothing2d.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_smoothing2d.py", line 27, in <module>
    B = Sop * A
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (231, 231), (11, 21)

-------------- plot_spread.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_spread.py", line 75, in <module>
    mlinwavR = RLop.H * mlinwav
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (20541, 100701), (201, 501)

-------------- plot_stacking.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_stacking.py", line 30, in <module>
    D2hop = pylops.SecondDerivative(dims=(11, 21), axis=1, dtype="float32")
TypeError: SecondDerivative.__init__() got an unexpected keyword argument 'axis'

-------------- plot_sum.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_sum.py", line 22, in <module>
    Sop = pylops.Sum(dims=(ny, nx), axis=0)
TypeError: Sum.__init__() got an unexpected keyword argument 'axis'

-------------- plot_symmetrize.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_symmetrize.py", line 53, in <module>
    Sop = pylops.Symmetrize((nt, nx), axis=0)
TypeError: Symmetrize.__init__() got an unexpected keyword argument 'axis'

-------------- plot_transpose.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_transpose.py", line 29, in <module>
    y = Top * x
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (800, 800), (20, 40)

-------------- plot_tvreg.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_tvreg.py", line 65, in <module>
    xinv = pylops.optimization.leastsquares.regularized_inversion(
AttributeError: module 'pylops.optimization.leastsquares' has no attribute 'regularized_inversion'. Did you mean: 'RegularizedInversion'?

-------------- plot_wavelet.py ----------- 

/home/evan/resources/venv3/lib/python3.10/site-packages/pywt/_multilevel.py:43: UserWarning: Level value of 5 is too high: all coefficients will experience boundary effects.
  warnings.warn(
Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_wavelet.py", line 51, in <module>
    y = Wop * im
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 91, in __mul__
    y = super().__mul__(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/scipy/sparse/linalg/_interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 262, in dot
    return self.matmat(x)
  File "/home/evan/resources/venv3/lib/python3.10/site-packages/pylops/LinearOperator.py", line 207, in matmat
    raise ValueError("dimension mismatch: %r, %r" % (self.shape, X.shape))
ValueError: dimension mismatch: (16384, 15876), (126, 126)

-------------- plot_wavest.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_wavest.py", line 135, in <module>
    ) = pylops.optimization.leastsquares.regularized_inversion(
AttributeError: module 'pylops.optimization.leastsquares' has no attribute 'regularized_inversion'. Did you mean: 'RegularizedInversion'?

-------------- plot_wavs.py ----------- 

Traceback (most recent call last):
  File "/home/evan/resources/pylops/examples/plot_wavs.py", line 29, in <module>
    wk, twk, wgk = pylops.utils.wavelets.klauder(t, f=[4, 30], taper=np.hanning)
AttributeError: module 'pylops.utils.wavelets' has no attribute 'klauder'

</pre>

</details>

**Comment by mrava87** [comment]
Hello, you are trying to run the code from our `latest` documentation. To be able to run it you need to have installed pylops directly from the `dev` branch. You are correct that we are making some API changes and soon will release pylops v2. 

However, if you prefer, and for now I would highly recommend that, you can use our stable version of the doc https://pylops.readthedocs.io/en/stable/, all of the examples here work with the latest pylops version (v1.18.2) that you can install via PyPI or Conda.

**Comment by mrava87** [comment]
FYI, we run all examples are run on readthedocs to rended the documentation that you see. This way allows us to be sure examples are always working fine with the correct version of pylops (latest -> dev, stable -> last pypi release).

**Comment by Evidlo** [comment]
You're right, sorry for the noise.
